config/routes.rb
Usydconnect::Application.routes.draw do
  get "users/new"
  
  root "static_pages#home"

  match("/login", to: "static_pages#create", via: "post")
  match("/help", to: "static_pages#help", via: "get")
  match("/about", to: "static_pages#about", via: "get")
  match("/policy", to: "static_pages#policy", via: "get")
  match("/signout", to: "static_pages#destroy", via: "delete")

  match("/new", to: "users#create", via: "post")
  match("/signup", to: "users#new", via: "get")

  

end

app/models/user.rb
class User < ActiveRecord::Base
 before_save { self.email = email.downcase }
 validates :username, uniqueness: { case_sensitive: false },
 					  presence: true, 
 					  length: { maximum: 15 }

 validates :password, presence: true, 
 					  length: { minimum: 6 }

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[sydney]+\.[edu]+\.[au]+\z/i

 validates :email, uniqueness: { case_sensitive: false }, 
 					  presence: true, 
 					  format: { with: VALID_EMAIL_REGEX }
 					  
 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Validates credentials to allow access to restricted pages
  def is_logged_in?
  	username = cookies.signed[:username]
  	password = cookies.signed[:pwd]
  	
  	if username.nil? || password.nil?
  		false
  	elsif password.empty? || username.empty? 
  		false
  	else
      true
  	end
  end
  
  def valid_login(user, pass)
	if user = User.where(username: user)
	  true
	else
	  false
	end
  end

	# Creates signed user cookies
	def create_cookies(username, password)
		cookies.signed[:username] = { 
	 		value: username,
	 		expires: 1.weeks.from_now }
	 	cookies.signed[:pwd] = {
	 		value: password,
	 		expires: 1.weeks.from_now }
	end

  # Destroy cookies
	def sign_out
		cookies.delete(:username)
		cookies.delete(:pwd)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def create
	if valid_login(params[:username], params[:password])
      password_hash = params[:password]
	  create_cookies(params[:username], params[:password])
	end
    redirect_to root_path
  end
  
  def destroy
  	sign_out
  	redirect_to root_path
  end
  
  def home
    @user = User.find(:all)
  end

  def help
  end

  def about
  end

  def policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # creates a new user, handles signup failure
  def create
    @user = User.new(user_params)
    if @user.save
	    create_cookies(params[:username], params[:password])
      flash[:success] = "Thank you for your registration at Usyd Connect. You will be redirected shortly."
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # Action for displaying a user's profile
  def show
    @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# Returns "No Title" if no provided title, else use provided title.
	def full_title(page_title)
		base_title = "No Title"
		if page_title.empty?
			base_title
		else
			"#{page_title}"
		end
	end
	
	def is_logged_in?
  	username = cookies.signed[:username]
  	password = cookies.signed[:pwd]
  	
  	if username.nil? || password.nil?
  		false
  	elsif password.empty? || username.empty? 
  		false
  	else
      true
  	end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div id="footer-link">
		<%= link_to("About", about_path) %>
		-
		<%= link_to("Help", help_path) %>
		-
		<%= link_to("Policy", policy_path) %>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="header">
		<div id="header-inner">
			<%= link_to(image_tag("logo.png", id: "logo"), root_path) %>
			<%= link_to("USYD Connect", root_path, id: "title") %>
			<div id="sign">
				<% if !is_logged_in? %>
					<%= form_tag('/login', method: 'post') do %>
						<%= text_field_tag(:username, "", :placeholder => " username", :class => "text-field", :maxlength => 16)%>
						<%= password_field_tag(:password, "", :placeholder => " password", :class => "text-field", :maxlength => 16)%>
						<%= submit_tag("Login", id: "button")%>
						<%= link_to("<button>Sign Up</button>".html_safe, signup_path, id: "button")%>
					<% end %>
				<% else %>
					Logged in as: <i> to be implemented </i>
					<%= link_to("<button>Sign Out</button>".html_safe, signout_path, { :method => "delete" })%>
				<% end %>
			</div>
		</div>
	</div>
	<div class="nav">
		<% if !is_logged_in? %>
			<ul id="nav">
				<li class="navitem"><%= link_to("Home", root_path, :class => "link")%></li>
				<li>&nbsp</li>
			</ul>
		<% else %>
			<ul id="nav">
				<li class="navitem"><%= link_to("Home", root_path, :class => "link")%></li>
				<li>&nbsp</li>
				<li class="navitem"><%= link_to("Following", '#', :class => "link")%></li>
				<li>&nbsp</li>
				<li class="navitem"><%= link_to("Profile", '#', :class => "link")%></li>
				<li id="gap">&nbsp</li>
				<li class="navitem"><%= link_to("New Thread", '#', :class => "link")%></li>
			</ul>
		<% end %>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%# Dynamically generate a title for every page. %>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag("application", { media: "all", "data-turbolinks-track" => true } ) %>
		<%= javascript_include_tag("application", "data-turbolinks-track" => true) %>
		<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
	<%= render "layouts/header" %>
		<div id="content" class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</div>
		&nbsp
	
		<%= render "layouts/footer" %>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The following errors occurred during your sign up
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
	<%# Generate title. %>
	<% provide(:title, 'About') %>

	<body>
		<div class="content">
			<div>
				<div>
					<br>
					<br>
					<h2>About Us</h2>
					<p> Don't know about USYD-Connect? Read below to find out who we are!</p>
			
					<div id="what_do_we_do">
						<h3> Who are we?</h3>
						<p>
							USYD-Connect is run by five core team members
							<li> Henry Su </li>
							<li> Brian Mok </li>
							<li> Rick Ni</li> 
							<li> Catherine Yousheyah </li>
							<li> Mark Angelo Lim </li>
						</p>
						<h3> Our motivation </h3> 
						<p> 
							As a student, have you ever asked yourself, "How do I know if this subject is right for me?" or, "What subjects should I even pick for next semester?" To answer this question, students were often limited to the following ways:
								<ul>
									 <li> Physically ask or communicate online for opinion from a student that has previously taken the subject </li>
									 <li> Arrange an appointment with a lecturer to discuss the subject </li>
									 <li> Search the USYD website for the subject's official course outline.</li>
								</ul>
							</br>
							We realise that not everyone may know someone that has previously taken the subject, or they might not have the time to arrange an appointment with the lecturer. With USYD-Connect, we aim to help solve this problem. 
						</p>
						<h3> What do we do? </h3>
						<p>
							USYD-Connect serves as an information hub for the USYD community where staff and students interact casually in a forum environment. More specifically, our services allow users to register their a profile and participate in the forum by posting and answering questions. Through this, we are able to create an online forum where students can easily seek the answers that they desire.  
						</p>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
	<%# Generate title. %>
	<% provide(:title, 'Help') %>
	<body>
		<div class="content">
			<h2> Help! </h2>
			<p> If you're having problems, read the followng FAQs before contacting moderators.</p>
			<ol>
				<li><h4> Why can't I access USYD Connect? </h4></li>
					<p> Given the content of this forum is targeted at the USYD community, only those with a USYD email domain are able to access this service. Otherwise, it is possible you have entered in the wrong username password combination into our system and it cannot be verified. Please ensure your details are correct. If you suspect you have been banned from the forum, please contact one of the moderators to seek further details.</p>
				<li><h4> How do I post anything on USYD Connect? </h4></li>
					<p> Firstly, a USYD Connect account is required to post any content on the forum. Secondly, you must remain signed during the posting process. </p>
				<li><h4> How do I change my user and private settings? </h4></li>
					<p> Go to your user profile located on the navigation bar when logged in to edit your settings. </p>
				<li><h4> Where are your policies listed? </h3></li>
					<p> Click on the folloing <%= link_to("Policy", policy_path) %> page to find out more</p>
			</ol>
		</div>
	</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
	<%# Generate title. %>
	<% provide(:title, 'Home') %>


	<body>
		<div class="content">
			<div id="content">
				<br>
				<div id="search">
				<table>
					<%= form_tag('/search', method: '#') do %>
						<td><%= text_field_tag(:search, "", :placeholder => "  search", :class => "search-field")%></td>
						<td><%= link_to(image_tag("dropdownarrow.png", id: "dropdown"), '#') %></td>
						<td><%= submit_tag("Search", id: "search-button")%></td>
					<% end %>
				</table>
	                  
				</div>
				  <br>
					NOTE! DO NOT SEARCH! WILL ERROR!
					<h1>Tasks to do:</h1>
				<p>
					make the tabs change color so that the current tab is highlighted.
					<br>
					login button looks weird on safari.
					signup button looks weird on chrome.
					needs fixing!!!
				</p>
			
				<% @user.each do |u| %>
				<%= u.username %>
				<br>
				<% end %>
				<br>
				<p>
					This is the link to tutorials: 
					<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
				</p>



					<div id="test" onclick="test()">
						hello world!
					</div>
					<br>
					<br>

			
				<table>
					<tr>
						<div id="pinned">
							<div id="table-content">
								
									<div id="table-title">
										
											Pinned
										
									</div>
									<ul>
										<li>a</li>
										<li>b</li>
									</ul>
							</div>
						</div>
					</tr>

						<tr>
							<div id="recent">
								<div id="table-content">
									<div id="table-title">Recent Posts</div>
									<ul>
										<li>a</li>
										<li>b</li>
									</ul>
								</div>
							</div>
						</tr>


					<tr>
						
							<div id="categories">
								<div id="table-content">
									<div id="table-title">Categories</div>
									<ul>
										<li>a</li>
										<li>b</li>
									</ul>
								</div>

							</div>
						</tr>
						
				</table>

				


			</div>




		</div>

		

	

	</body>
</html>

app/views/static_pages/policy.html.erb
<!DOCTYPE html>
<html>
	<%# Generate title. %>
	<% provide(:title, 'Policy') %>

	<body>

		<div class="content">
		<div id="content">
			<div id="random">
				<h2>Terms and Conditions / Privacy Statement / Disclaimer</h2>
				<strong><p>Please read the following Terms and Conditions, Privacy Statement, and Disclaimer carefully as they apply to your use of this site at http://usydconnect.herokuapp.com. 
				</p></strong>
						<br/>
				<p>In using this site, one is deemed a "USYD Connect user" and is required to follow all of the following Terms and Conditions. In the case that one finds disagreement with any of the Terms and Conditions, the one in regard must discontinue use of this site immediately. USYD Connect assumes no liability nor ownership of any information, files, links posted on http://usydconnect.herokuapp.com, and any consequences regarding misuse of any of our services. 
				</p>
			</div>
						<br/>			
			<div id="terms">
				<h4>1. User Eligibility</h4>
				<p>USYD Connect is available for use for all University of Sydney staff and students; who register with a valid University of Sydney email address. 
				</p>
						<br/>
				<h4>2. Posting</h4>
				<p>Content made or posted by users of USYD Connect are considered the intellectual property of the person who posted or made the content in regard. USYD Connect does not own anything posted by its users. Registered users of USYD Connect are assumed to have agreed not to violate the Terms and Conditions. In the case that such agreement is breached, the user shall accept the sentence placed upon them.
				</p>
						<br/>			
				<h4>3. Multimedia</h4>
				<p>Images, Videos, and any other multimedia may be embedded in posts but are not hosted by USYD Connect. If you believe that any of your copyrighted content is displayed on USYD Connect, please directly contact the companies hosting your content. 
				</p>
						<br/>
				<h4>Responsibility of Actions</h4>
				Sharing of registered accounts is permitted but not recommended. The owner of a registered account shall assume all liability for all actions, and all consequences regarding any misconduct committed on their account. 
			</div>
						<br/>	
			<div id="privacy">
				<h3>Privacy Statement</h3>
				<p>USYD Connect puts the protection of the privacy of its users in high regard, and handles personal information in utmost levels of confidentiality that we are capable of. Any information that users directly supply, such as through registration (when registering on our site, you may be asked to enter your: name or e-mail address	- you may, however, visit our site anonymously.), and through posting, may be collected and used in one of the following ways:
				</p>
						<br/>
				<p><ul>
					<li>- To personalise user experience</li>
					<li>(your information will help us find what is more suitable for your individual needs)</li>
						<br/>
					<li>- To improve our site</li>
					<li>(your information and feedback we receive from you will aid us in improving services on our site)</li>
						<br/>
					<li>- To improve customer service</li>
					<li>(your information helps us to respond to your customer service requests more effectively)</li>
						<br/>
					<li>- To process transactions</li>
					<li><blockquote>Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent.</blockquote></li>
					<li>- To send periodic emails</li>
					<li>(The email address you provide may be used to send you information, respond to inquiries, and/or other requests or questions.)</li>
						<br/>
				</ul></p>
				<p><strong>Use of Cookies</strong>
				USYD Connect may use cookies to collect online traffic data, and to remember your preferences.
				</p>
			</div>
						<br/>
			<div id="disclaimer">
				<p>By using our site, you consent to our website Privacy Policy, and accept our Terms and Conditions. 
				</p>
						<br/>
				<p>If any changes are made to our privacy policy, we will send an email notifying you of any changes, and/or update the Privacy Policy modification date below.
				</p>
						<br/><br/>
				<p>Policy last updated on: 26/09/2013
				</p>
						<br/><br/><br/>
			</div>
		</div>
		</div>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
    <html>
    <% provide(:title, 'Sign up') %>
   

    <body>

        <div class="content">
            <div id="content">

     <h1>Sign up</h1>

                    <%= form_tag('/new', method: 'post') do %>
                        <table id="signup">
                            <tr>
                                <td><%= label_tag :username %></td>
                                <td><%= text_field_tag :username %></td>
                            </tr>
                            <tr>
                                <td><%= label_tag :email %></td>
                                <td><%= text_field_tag :email %></td>
                            </tr>
                            <tr>
                                <td><%= label_tag :password %></td>
                                <td><%= password_field_tag :password %></td>
                            </tr>
                        </table>
                        <br>
                        <%= submit_tag("Sign up")%>
                    <% end %>

                    <br>
                     <p>
            add realtime checking if name is available.<br>
            add a new input field for verification. this field appears when user clicks signup. the signup button will change to "verify". add function to randomly generate and email verification code. add function to check if verification code is correct.<br>
            also, make sure this page is not available to users that have already logged in. ie, if i type the URL address /signup while im logged in, it should error.
        </p>
            </div>
        </div>


    </body>
</html>

app/views/users/profile.html.erb
<% provide(:title, 'Profile') %>
<h1><%= @user.name %></h1>

<%= @user.name %>, <%= @user.email %>